#!/bin/zsh
rm -f ./build/html5panel.zxp \
&&  zxpsigncmd -sign ./dist ./build/html5panel.zxp lumens.p12 $1 -tsa https://timestamp.geotrust.com/tsa \
&& open ./build/html5panel.zxp

#&& rm -f ../savepanel_cc.zxp \
#&& zxpsigncmd -sign hybrid ../tychpanel_cc.zxp lumens.p12 $1 -tsa https://timestamp.geotrust.com/tsa \
